name: Vulnerable Workflow
on: push
jobs:
  insecure_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: curl
        run:  curl -s https://webhook.site/dae90d7f-137c-43ae-af02-c964d8e53035
